
services:

    # PHP Service
    app:
        build:
            args:
                user: user
                uid: 1000
            context: .
            dockerfile: docker/php/Dockerfile
        image: app
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./vendor:/var/www/vendor
            - ./storage:/var/www/storage
        depends_on:
            - database
        networks:
            - app-network

    # MySQL Service
    database:
        image: mysql:8.2
        container_name: database
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: shop
            MYSQL_USER: user
            MYSQL_PASSWORD: pass
            MYSQL_ROOT_PASSWORD: pass
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - app-network

    # Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - app-network

volumes:
    mysql_data:
        driver: local

# Networks Configuration
networks:
    app-network:
        driver: bridge
